controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

settings_test:
    path: /app/singleton_test
    controller: App\Controller\SettingsTestController::singletonTest

factory_test:
    path: /app/factory_test
    controller: App\Controller\FactoryTestController::factoryTest

observer_test:
    path: /app/observer_test
    controller: App\Controller\ObserverTestController::observerTest

strategy_test:
    path: /app/strategy_test/{strategy}
    controller: App\Controller\StrategyTestController::strategyTest

builder_test:
    path: /app/builder_test
    controller: App\Controller\BuilderTestController::builderTest

adapter_test:
    path: /app/adapter_test
    controller: App\Controller\AdapterTestController::adapterTest

decorator_test:
    path: /app/decorator_test
    controller: App\Controller\DecoratorTestController::decoratorTest

prototype_test:
    path: /app/prototype_test
    controller: App\Controller\PrototypeTestController::prototypeTest

facade_test:
    path: /app/facade_test
    controller: App\Controller\FacadeTestController::facadeTest

proxy_test:
    path: /app/proxy_test
    controller: App\Controller\ProxyTestController::proxyTest

CoR_test:
    path: /app/chainOfResponsibility_test
    controller: App\Controller\ChainOfResponsibilityController::corTest