controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

settings_test:
    path: /app/settings_test
    controller: App\Controller\SettingsTestController::showMessage

factory_test:
    path: /app/animalFactory_test
    controller: App\Controller\FactoryTestController::testFactory

observer_test:
    path: /app/observer_test
    controller: App\Controller\ObserverTestController::observerTest